### ISSUE TITLE
Problem: `WaitTx` is misleading about errors

### ISSUE THREAD

**Issue by outerlook** [trufnetwork/sdk-go#8]
> Ah yes, forget to mention that.
> 
> err doesn't catch the error.
> 
> To catch the error it needs to call waitTx.
> It is inside one of the fields.
> 
> Maybe some extra conditional like --sync flag would do.

_Originally posted by @MicBun in https://github.com/truflation/tsn-sdk/issues/7#issuecomment-2231341537_

> That's right... we have another way shown here: [main/tests/integration/util.go#L35](https://github.com/truflation/tsn-sdk/blob/main/tests/integration/util.go?rgh-link-date=2024-07-16T16%3A26%3A47Z#L35)
> this checks if the transaction received an OK status. however it might be good to create a helper for that

**Comment by MicBun** [comment]
I believe this issue has been resolved as our commits have gradually made the error details more comprehensive.
cc @outerlook
